//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

		public class item:MonoBehaviour
		{
			
			public int puntos=0;
			public bool pickable=false;
	public bool isPicked=false;

	public AudioClip SonidoAlDestruir;

	void OnDestroy(){
		if (SonidoAlDestruir!=null && isPicked){
			Sonido.PlayFX(transform.position,this.SonidoAlDestruir);
		}
	}
		}

